### ISSUE TITLE
IndexedDB tab generates error on 2 different Chromebooks

### ISSUE THREAD

**Issue by hardwareMike** [AndreLion/html5-localstorage-manager#11]
Click on app icon.
Click on indexedDB tab.
Click on Open in New Window.
Get:
'404. That’s an error.

The requested URL /chrome-extension-localstorage-manager-popup-404.html was not found on this server. That’s all we know.'

I have 2 different up to date Chromebooks.  That is the only error message I got.

**Comment by ofavre** [comment]
I came across this error while testing it on google.com.
The way it works (opening a popup in the domain using an nonexistent URL then replacing content of the returned 404 page) is quite strange at first, it's true.
Is the popup necessary for IndexedDB?
