### ISSUE TITLE
No Longer Working in Chrome 40.0.2214.91 m

### ISSUE THREAD

**Issue by miguelsolorio** [AndreLion/html5-localstorage-manager#13]
Once my Chrome browser updated to Version 40.0.2214.91 m, the extension no longer works and does not appear in the search bar (even with enabling "Always show the orange icon in address bar"). I've removed the extension and re-loaded, enabling/disabling, with no success.

System:
Chrome 40.0.2214.91 m
Windows 8.1

**Comment by AndreLion** [comment]
This problem occurs before sometimes and it's really annoying me and very difficult to debug. I'm guessing whether it's related to Chrome....

**Comment by AndreLion** [comment]
since Chrome 42, this issue hasn't appeared any more, and I did nothing for it. Seems like Google has improved the extension stability. So close it.
