### ISSUE TITLE
Would love to use this when developing Chrome Extensions, but needs a hotkey.

### ISSUE THREAD

**Issue by iDVB** [AndreLion/html5-localstorage-manager#14]
There is no way to access this when developing in a Chrome 'panel' or 'normal' window.
It might work if there was a way to pop this up via a hotkey.

**Comment by AndreLion** [comment]
Do you mean to active this extension via a hotkey?

**Comment by iDVB** [comment]
Exactly. More specifically, when debugging Chrome extension DEV.

D
