### ISSUE TITLE
Whitelist/blacklist functionality

### ISSUE THREAD

**Issue by gkiely** [AndreLion/html5-localstorage-manager#15]
Would be great if it was possible to enable just for localhost or other specified development url.

**Comment by AndreLion** [comment]
what's wrong with enabling with global url? Does it slow down the loading of page or what?

**Comment by gkiely** [comment]
Purely a UI aspect, I would just prefer to only show the icon for localhost.

**Comment by AndreLion** [comment]
Sure. that sounds reasonable

**Comment by gkiely** [comment]
Thanks @AndreLion
