### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by schoes** [AndreLion/html5-localstorage-manager#22]
Under which licence is the manager developed

**Comment by AndreLion** [comment]
No license attached by this project so far.
Anything I can help?

**Comment by schoes** [comment]
Can this extension be used in enterprise environment ?

**Comment by AndreLion** [comment]
Looks like there is no difference than installing this extension from Google web store and use it in Chrome?
Am I correct?

**Comment by schoes** [comment]
so you would say there is no problem using this extension in a enterprise ?

**Comment by AndreLion** [comment]
Exactly. Go ahead and use it.
And please report any issue while you are using or suggest if anything can be improved.
