### ISSUE TITLE
404 not found?

### ISSUE THREAD

**Issue by leocaseiro** [AndreLion/html5-localstorage-manager#29]
Hi, for some reason, the extension is no longer available, do you know what happened?

see 
https://chrome.google.com/webstore/detail/html5-localstorage-manage/giompennnhheakjcnobejbnjgbbkmdnd

Thanks

**Comment by AndreLion** [comment]
Because it was taken down by Google due to some policy change.
Let me update the code and bring it back asap.
Sorry for the inconvenience.

**Comment by leocaseiro** [comment]
Thanks for that

**Comment by Procyon-b** [comment]
I wish you the best, interacting with the reviewers of the web store.   ;)

If you find a reliable way to get answers to your questions (if you had some), could you please post here?
I have 3 extensions that will soon need to be updated (fixes and enhancements), and I know that for at least 2 of them I'll get the same problem of being refused on the first try.

**Comment by leocaseiro** [comment]
If you are not having luck, this might be inspiring. https://medium.com/@miko_89964/after-3-years-of-work-chrome-killed-my-extension-and-wont-tell-me-why-83a3f8d65cbc

Btw, if you get reject or something, please put the results here, I love your extension, and I would be happy to help you out.

**Comment by Procyon-b** [comment]
@leocaseiro thanks for the info.

**Comment by AndreLion** [comment]
Hi all, thanks for your info and patience.
Now the extension is back to chrome web store:
https://chrome.google.com/webstore/detail/realtime-json-friendly-lo/giompennnhheakjcnobejbnjgbbkmdnd/related

It comes with a new design and providing complementary features than native chrome devtool. Please install or upgrade it.

Thanks again and have a nice weekend.
