### ISSUE TITLE
Extension throws 404 error when clicking icon in address bar

### ISSUE THREAD

**Issue by davelaflam** [AndreLion/html5-localstorage-manager#4]
Using Chrome version 37.0.2062.124
The extension works fine but when clicking the icon in the address bar it throws the following error:
chrome-extension-localstorage-manager-iframe-notification-404.html 404 (Not Found) 
Request URL:http://localhost:9090/chrome-extension-localstorage-manager-iframe-notification-404.html
Request Method:GET
Status Code:404 Not Found

**Comment by iframe-notification-404** [comment]
But it's not just _reporting_ a 404, it's actually making a request for the page "chrome-extension-localstorage-manager-iframe-notification-404.html" from whatever website you happen to be viewing.

Which means the fact that I am using this extension is being reported to the owner of the website - which is unacceptable.

It fully loads the 404 page, as well as any images and javascript on that page.

People don't like it when apps and extensions "phone home", so why do you think that people would be okay with their extensions "phoning out" like this?

I have added "chrome-extension-localstorage-manager-iframe-notification-404.html" to ublock, and the localstorage manager works fine.

I advise anyone else to do the same: or just stop using this extension.
