### ISSUE TITLE
Anyone using indexedDB?

### ISSUE THREAD

**Issue by AndreLion** [AndreLion/html5-localstorage-manager#8]
If you are using indexDB in your website, and you need a tool to debug it. Please let me know.

Thanks.

**Comment by ofavre** [comment]
`add`/`put`/`delete` features for IndexedDB would be awesome.
I can't find any extension doing this, even the Dev Tools do not (though they do for the localStorage).

**Comment by AndreLion** [comment]
No request, no update.
thanks for your comment, will update soon.

**Comment by akupiec** [comment]
+1 for add / put / delete

**Comment by franciscocabral** [comment]
+1 for add / put / delete

**Comment by CRuppert** [comment]
exports too please. having this tool would ahve saved us writing our own today.

**Comment by geoidesic** [comment]
Yes please. I tried your beta extension for this and while it claims to have connected to the indexedDB database it's not providing any actual functionality?

**Comment by AndreLion** [comment]
Hi @geoidesic , is there anything that indexedDB chrome devtool can not satisfy you? So that I can provide better function and experience to more developers.

**Comment by AndreLion** [comment]
In version 2.0. IndexedDB is not supported anymore.
